import type { Metadata } from "next";
import { Open_Sans, Libre_Baskerville } from "next/font/google";
import '@/styles/globals.css'
import LayoutWrapper from "@/components/common/layoutWrapper";
import { ThemeProvider } from "@mui/material";
import { theme } from "@/styles/theme";

const libreBaskerville = Libre_Baskerville({
  variable: "--font-libre-baskerville",
  subsets: ["latin"],
  weight: "400",
  style:['normal', 'italic']
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "All Care for Everyone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="description" content="All Care for Everyone" />
        <meta name="keywords" content="All Care for Everyone" />
        <meta name="author" content="All Care for Everyone" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={`${openSans.variable} ${libreBaskerville.variable} antialiased`}
      >
        <ThemeProvider theme={theme}>
          <LayoutWrapper>{children}</LayoutWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}

